# Generated by Django 3.1.5 on 2021-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210130_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='published_at',
        ),
        migrations.AddField(
            model_name='specialty',
            name='title_special',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
