# Generated by Django 3.1.5 on 2021-02-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210201_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='title_special',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
