# Generated by Django 3.1.5 on 2021-02-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0008_auto_20210217_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128,
                region=None,
                unique=True,
                verbose_name='Телефон',
            ),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[
                    ('not', 'Не ищу работу'),
                    ('consider', 'Рассматриваю предложения'),
                    ('seek', 'Ищу работу')],
                    default='not',
                    max_length=15,
                    verbose_name='Готовность к работе'),
                 ),
                ('salary', models.PositiveIntegerField(verbose_name='Вознаграждение')),
                ('grade', models.CharField(
                    choices=[
                        ('intern', 'Стажер'),
                        ('junior', 'Джуниор'),
                        ('middle', 'Миддл'),
                        ('senior', 'Синьор'),
                        ('lead', 'Лид')],
                    default='intern',
                    max_length=20,
                    verbose_name='Квалификация'),
                 ),
                ('education', models.TextField(blank=True, default='', verbose_name='Образование')),
                ('experience', models.TextField(blank=True, default='', verbose_name='Опыт работы')),
                ('portfolio', models.URLField(blank=True, default='', verbose_name='Портфолио')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty',
                                                to='vacancies.specialty', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume',
                                              to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
